# Generated by Django 4.1.5 on 2023-01-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='long',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
