# Generated by Django 4.1.5 on 2023-01-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_track_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='picture',
            field=models.ImageField(default=1, upload_to='aLbumsimages'),
            preserve_default=False,
        ),
    ]
