# Generated by Django 4.1.5 on 2023-01-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_album_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albums', models.ManyToManyField(to='track.album')),
            ],
        ),
        migrations.DeleteModel(
            name='MyPlaylist',
        ),
    ]
